spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: nacos-consumer
          uri: lb://nacos-consumer
          predicates:
            - Path=/nacos-consumer/hello/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
        - id: youlai-auth
          uri: lb://youlai-auth
          predicates:
            - Path=/youlai-auth/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
